### ISSUE TITLE
[Combat] Battle Fatigue

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#1551] opened 2024-06-09 11:33 UTC
Battle Fatigue gets added as soon as you are in combat

Could be like 1 min of combat = 2 Battle Fatigue

Only entertainers can heal BF

Idea:
100 BF = +10% taken damage / -10% less damage ouput

**Comment by madsboddum** [comment] 2024-06-09 11:35
Duplicate of #597, I think?

**Closed** 2024-06-09 12:09 UTC
Labels: FEATURE
